trainingFolder = './training';
trainingSets = [
    imageSet(fullfile(trainingFolder, '/1. Almost Empty')), ...
    imageSet(fullfile(trainingFolder, '/2. Sparsely Crowded')), ... 
    imageSet(fullfile(trainingFolder, '/3. About Half Full')), ...
    imageSet(fullfile(trainingFolder, '/4. Very Crowded')), ...
    imageSet(fullfile(trainingFolder, '/5. Full')) ];
bag = bagOfFeatures(trainingSets);
img = read(trainingSets(1), 1);
featureVector = encode(bag, img);
categoryClassifier = trainImageCategoryClassifier(trainingSets, bag);
save('crowdClassifier.mat', 'categoryClassifier');